name: Update Ferry Schedule

on:
  schedule:
    # Run daily at 3:00 AM Brisbane time (17:00 UTC)
    - cron: '0 17 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd schedule-processor
        npm install
        
    - name: Run schedule processor
      run: |
        cd schedule-processor
        node process-schedule.js
        
    - name: Commit and push if changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        cd ${{ github.workspace }}
        git add schedule-data/
        git diff --staged --quiet || (git commit -m "Update ferry schedule data [skip ci]" && git push)